nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:4200'] # L'URL de ton projet Angular
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', POST', 'PUT', 'DELETE', 'OPTIONS']
  paths:
    '^/api/': null
